name: economyb-api
version: '${version}'
main: tech.cookiepower.economyb.api.EconomybApiPlugin
api-version: '1.21'
commands:
  economy:
    description: The main command for EconomybAPI
    usage: /<command>
    aliases: [eco, economyb]
    permission: economyb.command.economy
    permission-message: You do not have permission to use this command.
    default: op